feat: добавить возможность бронирования вещи
I-Wish-I-Knew/java-shareit pull request #2
Opened 2022-10-02 12:46 UTC by I-Wish-I-Knew

feat: добавить возможность оставлять комментарии вещи
refactor: сделать JPA репозитории для Item и User

2022-10-02 18:15 UTC, Frilock requested changes
Добрый вечер, очень прилично, мне все нравится. Пара небольших комментариев и жду повторно работу

2022-10-02 18:15 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "end_date")
Вообще по хорошему еще правильнее указывать размер полей, а так же, например, флаг not null, если поле не может быть null

2022-10-02 18:15 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +@Slf4j
Кажется аннотация лишняя, не вижу использования логгера

2022-10-02 18:15 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<BookingDtoInfo> getAllByOwner(State state, Long ownerId) {
По моему методы только идентификатором отличаются, а все внутри общее. Можем какой то приватный метод сделать, чтобы так код не дублировать?

2022-10-02 18:15 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.info(e.getMessage(), e);
А почему пишите в info, если у Вас ошибка? Логичнее как то в error писать

2022-10-02 18:15 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoInfo.java
> +        Long id;
Тогда бы для единообразия и тут приватные модификаторы увидеть

2022-10-02 18:15 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    @Transactional
А зачем над методами тогда ставите, если над классом есть? Тогда логичнее с класса убрать

2022-10-02 18:15 UTC, Frilock commented on src/main/resources/schema.sql
> +    user_id
Если честно такой скрипт выглядит не очень читаемо, предлагаю в 1 строчку одно поле писать с информацией о его свойствах

2022-10-03 11:11 UTC, I-Wish-I-Knew commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.info(e.getMessage(), e);
Ревьюер на групповом проекте сказал исправить логирование с log.error ошибок, которые известны. Что их нужно логировать на уровне info. Поэтому на error я оставила только handleUnexpectedError().

2022-10-03 11:15 UTC, I-Wish-I-Knew commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    @Transactional
Над классом я ставлю @Transactional(readOnly = true), а над методами которые должны ещё и писать ставлю просто @Transactional. У него по умолчанию readOnly = false

2022-10-03 13:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.info(e.getMessage(), e);
А чем он обосновал это?

2022-10-03 13:56 UTC, Frilock approved these changes
Принято, однако интересный момент про логирование, а чем это было обосновано от ревьювера?

2022-10-04 08:17 UTC, merged