15 спринт
I-Wish-I-Knew/java-shareit pull request #4
Opened 2022-10-18 10:07 UTC by I-Wish-I-Knew

feat: добавить ItemRequest
refactor: добавить тесты

2022-10-18 20:58 UTC, Frilock requested changes
Добрый день, в целом очень хорошая работа. Есть пара мелких комментариев. В некоторых тестах к полям потеряли модификаторы, в паре тестовых классов используете странный нейминг, поясните пожалуйста для чего.

2022-10-18 20:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +    private ItemRequestMapper() {
А зачем Вам пустой конструктор?

2022-10-18 20:58 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/storage/BookingStorageTest.java
> +        Optional<Booking> booking11 = bookingStorage.findBookingByIdAndBookerId(booking1.getId(),
Какой то странный нейминг полей. Для чего эти идентифкаторы? Вы можете в setUp чистить нужные Вам данные.

2022-10-18 20:58 UTC, Frilock commented on src/test/java/ru/practicum/shareit/item/comment/dto/CommentDtoInfoTest.java
> +    JacksonTester<CommentDtoInfo> json;
Модификатор приватный давайте проставим

2022-10-18 20:58 UTC, Frilock commented on src/test/java/ru/practicum/shareit/item/comment/CommentStorageTest.java
> +    UserStorage userStorage;
Модификатор забыли

2022-10-19 08:17 UTC, I-Wish-I-Knew commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +    private ItemRequestMapper() {
Это утилитный к класс, в котором только статические методы, для использования которых не нужно создавать экземпляр этого класса. Насколько я поняла, в таком случае это хорошая практика закрывать возможность создания экземпляра этого класса https://rules.sonarsource.com/java/RSPEC-1118.

2022-10-19 15:37 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +    private ItemRequestMapper() {
В целом да, можно вроде от ломбок использовать UtilityClass

2022-10-19 15:38 UTC, Frilock approved these changes
Добрый вечер, принято, хорошая работа!

2022-10-20 08:17 UTC, merged