TЗ 16
I-Wish-I-Knew/java-shareit pull request #5
Opened 2022-10-27 09:59 UTC by I-Wish-I-Knew

refactor: разделить на модули server и gateway
refactor: вынести валидацию в gateway
refactor: настроить запуск через docker

2022-10-28 13:37 UTC, Frilock requested changes
Добрый день, мне очень понравилась работа, все сделано очень хорошо. Еще понравилось что вы даже решили поиграться с реактором - здорово. Из комментариев, вижу только пару лишних аннотаций. Жду новую версию и приму работу.

2022-10-28 13:37 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Slf4j
Лишняя аннотация, не вижу использования логгера

2022-10-28 13:37 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +@Slf4j
По моему данная аннотация не используется

2022-10-28 13:37 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +@Slf4j
аналогично, проверьте в других местах

2022-10-28 13:37 UTC, Frilock commented on pom.xml
> +	</modules>
По гиту кажется что сьеъало форматирование

2022-10-28 13:37 UTC, Frilock commented on server/src/test/java/ru/practicum/shareit/item/comment/CommentStorageTest.java
> +        Assertions.assertThat(comments).hasSize(2)
А почему статический импорт решили убрать?

2022-10-30 11:09 UTC, I-Wish-I-Knew commented on pom.xml
> +	</modules>
Странно, в идее всё хорошо.

2022-10-30 14:51 UTC, Frilock approved these changes
Принято, отличная работа, удачи на дипломе

2022-12-23 13:37 UTC, merged